model:
  mem-units: 128

trainer:
  save_path: 'model'
  max-grad-norm: 999.
  max_episodes: 500_000

param_loss:
  name: A2C
  params:
    coef_valueloss: 0.05
    coef_entropyloss: 0.05
    gamma: 0.9

param_optim:
  name: RMSprop
  lr: 7.e-4

param_buffer:
  capacity: 1000
  mode_sample: last

param_logger:
  save_interval: 10_000
  resume: True


  
