save-path: model
save-interval: 10_000
resume: False

task:
  n_maxtrials: 30
  
a2c:
  mem-units: 128
  value-loss-weight: 0.05
  entropy-loss-weight: 0.05
  max-grad-norm: 999.
  gamma: 0.9
  lr: 7.e-4